# Generated by Django 3.0.2 on 2020-02-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200202_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cateory',
            new_name='category',
        ),
    ]
