# Generated by Django 3.0.2 on 2020-02-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200207_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='county',
            new_name='country',
        ),
    ]
