# Generated by Django 3.0.2 on 2020-03-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20200213_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Rating star', 'verbose_name_plural': 'Rating stars'},
        ),
    ]
